export const LANGUAGE_STORAGE_KEY = 'fqp-language';

export type AppLanguage = 'zh-CN' | 'en';

export const DEFAULT_LANGUAGE: AppLanguage = 'zh-CN';

export const LANGUAGE_OPTIONS: ReadonlyArray<{ value: AppLanguage; label: string; flag: string }> = [
  { value: 'zh-CN', label: '简体中文', flag: '🇨🇳' },
  { value: 'en', label: 'English', flag: '🇬🇧' },
];

const ENGLISH_TEXT: Record<string, string> = {
  '加载中...': 'Loading...',
  '加载数据中...': 'Loading data...',
  '加载失败': 'Failed to load',
  '登录失败': 'Sign-in failed',
  '重试': 'Retry',
  '暂无数据': 'No data available',
  '最后更新': 'Last updated',
  '页面不存在': 'Page not found',
  '路径': 'Path',
  '返回': 'Back',
  '取消': 'Cancel',
  '确认': 'Confirm',
  '保存': 'Save',
  '删除': 'Delete',
  '编辑': 'Edit',
  '关闭': 'Close',
  '刷新': 'Refresh',
  '筛选': 'Filter',
  '清除': 'Clear',
  '全部': 'All',
  '状态': 'Status',
  '操作': 'Actions',
  '日期': 'Date',
  '时间': 'Time',
  '类型': 'Type',
  '名称': 'Name',
  '详情': 'Details',
  '说明': 'Description',
  '加载页面...': 'Loading page...',
  '正在进入页面...': 'Opening page...',
  '正在进入投注中心...': 'Opening betting center...',
  '请输入访问密码': 'Enter access password',
  '登录': 'Sign in',
  '登录中...': 'Signing in...',
  '今日驾驶舱': 'Today dashboard',
  '比赛中心': 'Match center',
  '赛事中心': 'Event center',
  '投注中心': 'Betting center',
  '比赛结果': 'Match results',
  '推荐票单': 'Recommendation tickets',
  '复盘中心': 'Review center',
  '今日决策分析': 'Today decision analysis',
  '特征数据健康': 'Feature data health',
  '数据源与系统监控': 'Data sources and system monitor',
  '模块管理': 'Module management',
  '模型表现': 'Model performance',
  '模型接入': 'Model providers',
  '智能工作台': 'Agent workspace',
  '智能代理中心': 'Smart agent center',
  '冷门研究': 'Upset research',
  '策略验证': 'Strategy validation',
  '赔率走势': 'Odds movement',
  '足彩彩池': 'Football pools',
  '投注台': 'Betting terminal',
  '彩票': 'Tickets',
  '官方赛事选号、混合过关、倍数、注数与理论奖金': 'Official match picks, combos, multiples, bet count and projected prize',
  '我的彩票与智能代理的彩票，按日期归档': 'My tickets and agent tickets, archived by date',
  '结算后的盈亏、ROI、命中与趋势视图': 'Settled profit/loss, ROI, hits and trend views',
  '投注台生成票，彩票管理票，比赛结果看结算与盈亏': 'Create tickets, manage tickets, and review settlements and profit/loss',
  '投注中心视图': 'Betting center views',
  '点击进入': 'Open',
  '投注器': 'Betting terminal',
  '历史投注器': 'Historical betting terminal',
  '混合过关': 'Mixed combo',
  '时光机补录': 'Time machine entry',
  '刷新赔率': 'Refresh odds',
  '游戏规则': 'Game rules',
  '选择原投注业务日': 'Select original betting date',
  '暂无可补录日期': 'No dates available for entry',
  '正在读取历史官方比赛…': 'Loading historical official matches…',
  '正在读取官方开售比赛…': 'Loading official matches on sale…',
  '该日没有可补录的官方封盘赔率': 'No official closing odds are available for this date',
  '当前筛选条件下没有开售比赛': 'No matches on sale match the current filters',
  '官方赔率已发布，但当前未开放单关或过关，请稍后刷新。': 'Official odds are published, but no single or combo bets are open yet. Please refresh later.',
  '历史官方比赛': 'Historical official matches',
  '开售比赛': 'Matches on sale',
  '推荐投注': 'Recommended bets',
  '智能代理每日推荐': 'Daily agent recommendations',
  '虚拟 500 元用于记录模型表现，是否购买由你决定': 'A virtual ¥500 records model performance; whether to buy is your decision',
  '推荐加载失败': 'Failed to load recommendations',
  '正在读取推荐': 'Loading recommendations',
  '正在同步模型与官方在售赔率…': 'Syncing model output and official odds on sale…',
  '暂无推荐': 'No recommendations',
  '可信模型与官方赔率准备完成后会显示在这里。': 'Recommendations appear here when trusted models and official odds are ready.',
  '使用当前官方固定奖金加入投注器': 'Add to betting terminal using current official fixed odds',
  '当前官方投注器没有对应的可售选项': 'No matching option is on sale in the official betting terminal',
  '当前不可投': 'Unavailable',
  '票面预览': 'Ticket preview',
  '等待投注器生成票面': 'Waiting for a ticket preview',
  '从左侧加入推荐，或在中间投注器手工选号。': 'Add a recommendation from the left or choose picks manually in the terminal.',
  '来源': 'Source',
  '手工选号': 'Manual picks',
  '移除': 'Remove',
  '投注确认': 'Confirm bet',
  '过关方式': 'Combo type',
  '倍数': 'Multiple',
  '注数': 'Bet count',
  '投注金额': 'Stake',
  '理论最高奖金': 'Projected top prize',
  '保存中…': 'Saving…',
  '计算中…': 'Calculating…',
  '确认投注': 'Confirm bet',
  '投注单': 'Bet slip',
  '共计': 'Total',
  '注': 'bets',
  '元': 'yuan',
  '关': 'leg',
  '计算中': 'Calculating',
  '已选': 'Selected',
  '查看': 'View',
  '明细⌄': 'details⌄',
  '请选择过关': 'Select combo',
  '减少倍数': 'Decrease multiple',
  '当前倍数': 'Current multiple',
  '增加倍数': 'Increase multiple',
  '保存中': 'Saving',
  '确定': 'Confirm',
  '单票金额不能超过20,000元': 'A single ticket cannot exceed ¥20,000',
  '单场': 'Single',
  '未开售': 'Not on sale',
  '即将开赛': 'Starting soon',
  '对': 'vs',
  '让球数': 'Handicap',
  '全部游戏': 'All markets',
  '支持单场': 'single bet allowed',
  '不支持单场': 'single bet unavailable',
  '支持过关': 'combo allowed',
  '不支持过关': 'combo unavailable',
  '竞彩足球游戏规则': 'Football betting rules',
  '筛选比赛': 'Filter matches',
  '联赛': 'League',
  '全部赛事': 'All competitions',
  '仅看可单场投注': 'Show single bets only',
  '完成': 'Done',
  '知道了': 'Got it',
  '模拟投注明细': 'Betting details',
  '已保存到我的彩票': 'Saved to my tickets',
  '模拟金额': 'Simulated stake',
  '时光机补录说明': 'Time machine entry guide',
  '仅使用体彩官方编号比赛及停售前最后一次官方赔率。补录票会进入比赛结果和我的盈亏。': 'Only official Sporttery-numbered matches and the final official odds before closing are used. Entered tickets are included in match results and profit/loss.',
  '按历史官方封盘赔率重新录入真实彩票': 'Re-enter a real ticket using historical official closing odds',
  '可手工选号，也可接收左侧推荐投注': 'Choose picks manually or accept a recommendation from the left',
  '竞彩足球模拟试玩投注器': 'Football betting terminal',
  '投注器工具': 'Betting terminal tools',
  '有“单”标记的选项可投单场，其他至少选择2场比赛': 'Options marked “Single” can be bet individually; all others require at least two matches.',
  '赔率已锁定为官方停售前最后一次快照，补录后请人工核对票面。': 'Odds are locked to the last official snapshot before closing. Please verify the ticket manually after entry.',
  '比赛信息及固定奖金仅供参考，请以出票时刻为准。': 'Match information and fixed odds are for reference only; use the issued ticket as final.',
  '官方比赛加载失败': 'Failed to load official matches',
  '历史业务日加载失败': 'Failed to load historical business dates',
  '历史官方比赛加载失败': 'Failed to load historical official matches',
  '推荐投注加载失败': 'Failed to load recommended bets',
  '分析': ' analysis',
  '析': 'Analyze',
  '游戏': 'markets',
  '[主]': '[Home]',
  '过关': 'Combo',
  '竞猜结果按全场90分钟（含伤停补时）计算，加时赛和点球不计。': 'Results are settled on 90 minutes including stoppage time; extra time and penalties do not count.',
  '每注2元；页面中的1倍为基础投注，最高50倍。': 'Each bet costs ¥2. A 1x multiple is the base stake and the maximum is 50x.',
  '单场仅限带“单”标记的比赛；过关需选择2–8场。': 'Single bets are limited to matches marked “Single”; combos require 2–8 matches.',
  '同一场多个选择按复式备选展开，不会彼此串成一注。': 'Multiple picks in one match are treated as alternatives and are not combined with each other.',
  '胜平负/让球最多8关，总进球最多6关，比分/半全场最多4关。': 'Win-draw-win and handicap allow up to 8 legs; total goals up to 6; correct score and half/full time up to 4.',
  '单票金额不得超过20,000元。': 'A single ticket cannot exceed ¥20,000.',
  '单注奖金上限：单场10万元，2–3场20万元，4–5场50万元，6场及以上100万元；倍数另计。': 'Prize limits per bet are ¥100,000 for single, ¥200,000 for 2–3 matches, ¥500,000 for 4–5, and ¥1,000,000 for 6 or more; multiples are calculated separately.',
  '模型': 'Model',
  '市场': 'Market',
  '保本': 'Break-even',
  '市场 Edge': 'Market edge',
  '完整度': 'Completeness',
  '加入': 'Add',
  '场': 'matches',
  '项': 'picks',
  '倍': 'x',
};

const ENGLISH_SIDEBAR_GROUPS: Record<string, string> = {
  核心闭环: 'Core workflow',
  研究优化: 'Research',
  策略实验: 'Strategy lab',
  系统管理: 'System',
};

const ENGLISH_PANELS: Record<string, string> = {
  today_dashboard: 'Today dashboard',
  match_center: 'Match center',
  event_center: 'Event center',
  odds_movement: 'Odds movement',
  betting_center: 'Betting center',
  deep_analysis: 'Decision analysis',
  model_lab: 'Model performance',
  model_providers: 'Model providers',
  agent_workspace: 'Agent workspace',
  feature_snapshots: 'Feature health',
  upset_research: 'Upset research',
  backtest_lab: 'Strategy validation',
  pool_lottery: 'Football pools',
  data_health: 'System monitor',
  module_admin: 'Modules',
  settings: 'Settings',
  codex_console: 'Smart agents',
};

export function isAppLanguage(value: string | null): value is AppLanguage {
  return value === 'zh-CN' || value === 'en';
}

export function translateText(language: AppLanguage, text: string): string {
  if (language !== 'en') return text;
  return ENGLISH_TEXT[text] ?? text.replace(/^最后更新:\s*/, 'Last updated: ');
}

export function shellText(language: AppLanguage) {
  if (language === 'en') {
    return {
      accountActions: 'Account actions',
      language: 'Language',
      logout: 'Sign out',
      openMenu: 'Open menu',
      darkTheme: 'Switch to dark red theme',
      lightTheme: 'Switch to polar light theme',
    };
  }
  return {
    accountActions: '账户操作',
    language: '界面语言',
    logout: '退出登录',
    openMenu: '打开菜单',
    darkTheme: '切换黑红主题',
    lightTheme: '切换极地浅色',
  };
}

export function sidebarGroupLabel(language: AppLanguage, groupName: string): string {
  return language === 'en' ? ENGLISH_SIDEBAR_GROUPS[groupName] ?? groupName : groupName;
}

export function sidebarPanelLabel(language: AppLanguage, panelCode: string, fallback: string): string {
  return language === 'en' ? ENGLISH_PANELS[panelCode] ?? fallback : fallback;
}
